from athena.store import athena_db
from athena.models.jobs import Job, JobStatus, JobType, UserProfile, Skill
from uuid import uuid4
from datetime import datetime, UTC

# Create a test user profile
profile = UserProfile(
    id=uuid4(),
    email="chifuniro.phiri@consult-mw.com",
    full_name="Chifuniro Phiri",
    phone="+265 99 412 8890",
    location="Area 10, Lilongwe, Malawi",
    headline="Senior Technology & Operations Specialist",
    summary="Experienced professional with 10+ years in technology operations, software development, and team leadership.",
    skills=[
        Skill(name="Python", level="expert"),
        Skill(name="FastAPI", level="advanced"),
        Skill(name="React", level="advanced"),
        Skill(name="Docker", level="advanced"),
        Skill(name="Kubernetes", level="intermediate"),
        Skill(name="AWS", level="advanced"),
        Skill(name="PostgreSQL", level="intermediate"),
        Skill(name="Redis", level="intermediate"),
        Skill(name="CI/CD", level="advanced"),
        Skill(name="Team Leadership", level="advanced"),
    ],
    experience=[],
    education=[],
    certifications=[],
    hourly_rate_usd=50,
    expected_monthly_mwk=3500000,
    legal_authorized_signer="Chifuniro Phiri",
    linkedin_url="https://linkedin.com/in/chifuniro-phiri-mw",
    portfolio_url="https://github.com/chifuniro-phiri-systems",
    github_url="https://github.com/chifuniro-phiri-systems",
    preferences={
        "keywords": ["software engineer", "devops", "platform engineer"],
        "excluded_keywords": ["sales", "marketing"],
        "locations": ["Lilongwe", "Remote"],
        "job_types": ["full_time", "contract"],
        "min_salary": 60000,
        "preferred_sources": ["linkedin", "remote_ok"],
        "remote_only": True,
        "visa_sponsorship_required": False,
    },
    created_at=datetime.now(UTC),
    updated_at=datetime.now(UTC),
)
athena_db.user_profiles.add(profile)
print("Profile saved:", profile.full_name)

# Create sample jobs
sample_jobs = [
    Job(
        id=uuid4(),
        title="Senior Software Engineer",
        company="TechCorp Malawi",
        location="Lilongwe, Malawi",
        description="We are looking for a Senior Software Engineer to join our growing team. You will work on building scalable web applications using Python and React.",
        requirements=["Python", "FastAPI", "React", "PostgreSQL", "Docker", "AWS"],
        salary_or_budget="$80,000 - $120,000/year",
        deadline="2026-12-31",
        ats_score=92,
        posted_date="2026-09-01",
        status=JobStatus.SCORED,
        source="linkedin",
        application_url="https://linkedin.com/jobs/12345",
        job_type=JobType.FULL_TIME,
        category="job",
        scope="lilongwe-local",
        platform="linkedin",
        match_tier="excellent",
        match_score=92,
        match_reasons=[
            "Strong Python/FastAPI match",
            "React experience",
            "AWS knowledge",
        ],
        scraped_at=datetime.now(UTC),
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    ),
    Job(
        id=uuid4(),
        title="DevOps Engineer",
        company="CloudScale Inc",
        location="Remote",
        description="Join our DevOps team to build and maintain cloud infrastructure. Experience with Kubernetes, Docker, and CI/CD pipelines required.",
        requirements=["Kubernetes", "Docker", "AWS", "Terraform", "CI/CD", "Python"],
        salary_or_budget="$90,000 - $130,000/year",
        deadline="2026-11-30",
        ats_score=88,
        posted_date="2026-09-05",
        status=JobStatus.MATCHED,
        source="remote_ok",
        application_url="https://remoteok.io/jobs/67890",
        job_type=JobType.FULL_TIME,
        category="job",
        scope="remote-global",
        platform="remote_ok",
        match_tier="excellent",
        match_score=88,
        match_reasons=["Kubernetes expertise", "Docker experience", "CI/CD knowledge"],
        scraped_at=datetime.now(UTC),
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    ),
    Job(
        id=uuid4(),
        title="Platform Engineer",
        company="PlatformOps Ltd",
        location="Blantyre, Malawi",
        description="Platform Engineer needed to build internal developer platforms. Strong background in Kubernetes, service mesh, and developer experience.",
        requirements=[
            "Kubernetes",
            "Service Mesh",
            "Go",
            "Python",
            "Developer Platforms",
            "GitOps",
        ],
        salary_or_budget="$85,000 - $115,000/year",
        deadline="2026-10-31",
        ats_score=75,
        posted_date="2026-09-10",
        status=JobStatus.FETCHED,
        source="linkedin",
        application_url="https://linkedin.com/jobs/54321",
        job_type=JobType.FULL_TIME,
        category="job",
        scope="lilongwe-local",
        platform="linkedin",
        match_tier="good",
        match_score=75,
        match_reasons=[
            "Kubernetes experience",
            "Python skills",
            "Platform engineering",
        ],
        scraped_at=datetime.now(UTC),
        created_at=datetime.now(UTC),
        updated_at=datetime.now(UTC),
    ),
]

for job in sample_jobs:
    athena_db.upsert_job(job)
    print(f"Job saved: {job.title} at {job.company} ({job.status.value})")

print("Sample data seeded successfully!")
